### ISSUE TITLE
Another code review

### ISSUE THREAD

**Issue by Komosa** [narqo/go-badge#5]
- [ ] version.go file seems unused
- [ ] color.go: you shouldn't introduce constans ColorGrey and ColorGray, one is enough, using String() method to convert "green" to "#97ca00" is clever, but it looks rather like unnecessary hack :); also in example we can see, that Color type gives us some additional complexity which can be avoided
- [x] https://github.com/narqo/go-badge/blob/master/badge.go#L23 copypasted comment was never been true :P 
- [x] fonts/vera.go: move logic to `init()` function

generally, quite good code :)

**Comment by narqo** [comment]
Hey, @Komosa, thank you for review.

> you shouldn't introduce constants ColorGrey and ColorGray, one is enough

Those colour things have come from the original [colorscheme.json](https://github.com/badges/shields/blob/master/colorscheme.json) of shields.io project. But I agree that to have both looks quite redundant.

I couldn't think of good API to pass the colour. To have the constants like `ColorRed` looks more like a goway of doing this, at least standard `image/color` uses [it's colour variables](https://godoc.org/image/color#pkg-variables). But as you've written, to require `Color(c string)` instead of just `c string` looks overcomplicated.

> fonts/vera.go: move logic to init() function

I believe I should read about it, but are there guaranties that `init()` from the `badge` package will be invoked after `init()` from `fonts` has been finished?

**Comment by Komosa** [comment]
Yes: https://golang.org/ref/spec#Package_initialization
